### ISSUE TITLE
Quantum Algorithms to be added

### ISSUE THREAD

**Issue by kausthub-kannan** [kausthub-kannan/learnQC#3]
Here are the algorithms to be added to the docs along with the code if possible (The list will proceed to get more algorithms, do mention in the discussion if any new algorithm has to be added to the list)  

- [ ] [BB48 Protocol](https://github.com/kausthub-kannan/learnQC/issues/13)
- [ ] [Grover's Algorithm](https://github.com/kausthub-kannan/learnQC/issues/14)
- [ ] [CHSH inequality](https://github.com/kausthub-kannan/learnQC/issues/5)
- [ ] [Variational Eigensolver (VAE)](https://github.com/kausthub-kannan/learnQC/issues/6)
- [ ] [Shor's Algorithm](https://github.com/kausthub-kannan/learnQC/issues/7)
- [ ] [Simon's problem](https://github.com/kausthub-kannan/learnQC/issues/8)
- [ ] [Swamp Test](https://github.com/kausthub-kannan/learnQC/issues/9)
- [ ] [Quantum Wall Search](https://github.com/kausthub-kannan/learnQC/issues/10)
- [ ] [Amplitude amplification](https://github.com/kausthub-kannan/learnQC/issues/11)
- [ ] [Quantum Fourier Transform](https://github.com/kausthub-kannan/learnQC/issues/12)
